version: "3.4"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db

  backend:
    image: ghcr.io/cmarenburg/recipe-buddy-backend:master
    depends_on:
      - "mongo"

  frontend:
    image: ghcr.io/cmarenburg/recipe-buddy-frontend:master
    ports:
      - "4000:80"
    depends_on:
      - "backend"

volumes:
  mongo_db:
